functionsDirectory = "C:\\Users\\volk2\\Desktop\\gerry-deploy\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "."
functions = "netlify/functions"
functionsDirectory = "netlify/functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[env]

  [env.production]

[dev]
functions = "netlify/functions"

[functions]

  [functions."*"]
  node_bundler = "esbuild"